logging:
  level:
    com.teoresi.argo: DEBUG
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  file:
    name: logs/logfile_tmp.log
    rolling-file-name: logs/logfile-{yyyy-MM-dd}.log
    max-size: 512MB
    total-size-cap: 10GB
    clean-history-on-start: false

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: true

  flyway:
    enabled: false
    baselineOnMigrate: true
    validateOnMigrate: true
    locations:
      - classpath:mysql/schema
      - classpath:mysql/prod-data

application:
  cors:
    allowedOrigins: ${CORS_ALLOWED_ORIGINS}