server:
  port: 8080
  error:
    include-message: always

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

spring:
  application:
    name: @project.name@
    version: @project.version@
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: true
    time-zone: UTC
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Rome
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

app:
  upload:
    dir: ./uploads/allegati

application:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    cryptoKey: ${JWT_CRYPTO_KEY}
    tokenDurationMs: 1800000
    tokenRenewBeforeExpirationMs: 1800000